### ISSUE TITLE
RFC: WPGraphiQL IDE Merge Candidate Feature Tracking

### ISSUE THREAD

**Issue by josephfusco** [wp-graphql/wpgraphql-ide#1]
This issue is dedicated to tracking both the existing features of the current GraphiQL implementation in [wp-graphql](https://github.com/wp-graphql/wp-graphql), as well as highlighting some of the newer features that are included for 'free' by nature of updating to graphiql@3.

## ✨ GraphQL IDE Features

Below is a list of features in core wp-graphql that should be ported over in order to maintain feature parity.

- [x] https://github.com/wp-graphql/wpgraphql-ide/issues/3 
- [x] ~https://github.com/wp-graphql/wpgraphql-ide/issues/4~ (moving to phase 2)
- [x] https://github.com/wp-graphql/wpgraphql-ide/issues/5 (PR: #84) 
- [x] Scaffold E2E & Unit tests
- [x] ~Merge codebase into core WPGraphQL~ (covered by WPGraphQL's extension page)
  - [x] Setting(s) to enable/disable new and old GraphQL IDEs 
  - [x] ~GraphQL Admin Notice that let's folks know about the new IDE if they have not already activated it~ (covered by WPGraphQL's extension page)
- [x] ~Communicate new release~ (see https://github.com/wp-graphql/logistics-and-tracking/issues/62)
- [X] Prettify
- [x] ~[Full Screen Toggle](https://github.com/wp-graphql/wp-graphql/tree/develop/packages/graphiql-fullscreen-toggle)~ (with the drawer, we decided this wasn't necessary, at least right now)
- [x] #6

Some additional features from GraphiQL that should be verified to work as expected

- [X] Ability to update schema 🔄
- [X] Dark mode - verify colors make sense and text is legible

_Please comment below if I'm missing anything!_ 

## Pluggable Regions

![Pluggable Regions](https://github.com/wp-graphql/wpgraphql-ide/assets/6676674/3fa35a5f-8d72-4a69-a5ab-deaff1b90e5a)

## 📢 Feedback

Your feedback is welcome; start testing today!

```sh
composer require wp-graphql/wpgraphql-ide
```

or manually downloaded via project [releases](https://github.com/wp-graphql/wpgraphql-ide/releases).

**Comment by josephfusco** [comment]
> [Full Screen Toggle](https://github.com/wp-graphql/wp-graphql/tree/develop/packages/graphiql-fullscreen-toggle)

This feature _might_ be considered obsolete given the full width layout this implementation provides.
Ideally the drawer could "snap" to full screen [like this example](https://codesandbox.io/p/sandbox/drawer-non-dismissable-forked-jchtff?file=/app/my-drawer.tsx:1,1).

**Comment by josephfusco** [comment]
The current GraphiQL IDE page at `wp-admin/admin.php?page=graphiql-ide` enqueues it's own styles that conflict with this newer version. I believe this should be the only page that should be ignored while testing.

**Comment by josephfusco** [comment]
We are not merging WPGraphQL IDE into core WPGraphQL anymore, as it will be surfaced via the [extension's page](https://github.com/wp-graphql/wp-graphql/issues/3049)
