### ISSUE TITLE
General Review and Resubmission

### ISSUE THREAD

**Issue by josephfusco** [wp-graphql/wpgraphql-ide#196]
Blocked by #190, #191, #192, #193, #194, #195 

PR for the above ^ https://github.com/wp-graphql/wpgraphql-ide/pull/199

----

> "Once the issues we shared above are fixed, we will do a more in-depth review that might surface other issues."

## Acceptance Criteria
   - The plugin is free of all identified issues and has been resubmitted for review.

## Tasks
   - [x] Conduct a thorough review of the entire plugin codebase for any additional issues.
   - [x] Test the plugin to ensure it adheres to all WordPress guidelines.
   - [x] Upload the corrected version of the plugin to the WordPress repository.
   - [x] Reply to the WordPress Plugin Review Team's email to confirm the submission of the updated plugin.

**Comment by josephfusco** [comment]
Plugin was resubmitted as v4.0.0

[Image](https://github.com/user-attachments/assets/4383ff88-cbd2-4924-939a-f8f7e135e2f3)
